// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protocol.proto

package packet_protocol

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ProtocolID int32

const (
	ProtocolID_ProtocolBegin ProtocolID = 0
	ProtocolID_LoginReq      ProtocolID = 1
	ProtocolID_LoginRes      ProtocolID = 2
)

var ProtocolID_name = map[int32]string{
	0: "ProtocolBegin",
	1: "LoginReq",
	2: "LoginRes",
}

var ProtocolID_value = map[string]int32{
	"ProtocolBegin": 0,
	"LoginReq":      1,
	"LoginRes":      2,
}

func (x ProtocolID) String() string {
	return proto.EnumName(ProtocolID_name, int32(x))
}

func (ProtocolID) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_2bc2336598a3f7e0, []int{0}
}

func init() {
	proto.RegisterEnum("packet.protocol.ProtocolID", ProtocolID_name, ProtocolID_value)
}

func init() { proto.RegisterFile("protocol.proto", fileDescriptor_2bc2336598a3f7e0) }

var fileDescriptor_2bc2336598a3f7e0 = []byte{
	// 93 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2b, 0x28, 0xca, 0x2f,
	0xc9, 0x4f, 0xce, 0xcf, 0xd1, 0x03, 0x33, 0x84, 0xf8, 0x0b, 0x12, 0x93, 0xb3, 0x53, 0x4b, 0xf4,
	0x60, 0xc2, 0x5a, 0xd6, 0x5c, 0x5c, 0x01, 0x50, 0xb6, 0xa7, 0x8b, 0x90, 0x20, 0x17, 0x2f, 0x8c,
	0xe7, 0x94, 0x9a, 0x9e, 0x99, 0x27, 0xc0, 0x20, 0xc4, 0xc3, 0xc5, 0xe1, 0x93, 0x9f, 0x9e, 0x99,
	0x17, 0x94, 0x5a, 0x28, 0xc0, 0x88, 0xc4, 0x2b, 0x16, 0x60, 0x4a, 0x62, 0x03, 0x1b, 0x63, 0x0c,
	0x08, 0x00, 0x00, 0xff, 0xff, 0x0f, 0x09, 0xab, 0x8e, 0x66, 0x00, 0x00, 0x00,
}
