// Code generated by protoc-gen-go. DO NOT EDIT.
// source: login.proto

package packet_lobby

import (
	fmt "fmt"
	math "math"
	. "packet_returncode"

	proto "github.com/golang/protobuf/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type LoginReq struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginReq) Reset()         { *m = LoginReq{} }
func (m *LoginReq) String() string { return proto.CompactTextString(m) }
func (*LoginReq) ProtoMessage()    {}
func (*LoginReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_67c21677aa7f4e4f, []int{0}
}

func (m *LoginReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginReq.Unmarshal(m, b)
}
func (m *LoginReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginReq.Marshal(b, m, deterministic)
}
func (m *LoginReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginReq.Merge(m, src)
}
func (m *LoginReq) XXX_Size() int {
	return xxx_messageInfo_LoginReq.Size(m)
}
func (m *LoginReq) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginReq.DiscardUnknown(m)
}

var xxx_messageInfo_LoginReq proto.InternalMessageInfo

func (m *LoginReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type LoginRes struct {
	RetCode              ReturnCode `protobuf:"varint,1,opt,name=retCode,proto3,enum=packet.returncode.ReturnCode" json:"retCode,omitempty"`
	Uid                  int64      `protobuf:"varint,2,opt,name=uid,proto3" json:"uid,omitempty"`
	Name                 string     `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *LoginRes) Reset()         { *m = LoginRes{} }
func (m *LoginRes) String() string { return proto.CompactTextString(m) }
func (*LoginRes) ProtoMessage()    {}
func (*LoginRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_67c21677aa7f4e4f, []int{1}
}

func (m *LoginRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRes.Unmarshal(m, b)
}
func (m *LoginRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRes.Marshal(b, m, deterministic)
}
func (m *LoginRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRes.Merge(m, src)
}
func (m *LoginRes) XXX_Size() int {
	return xxx_messageInfo_LoginRes.Size(m)
}
func (m *LoginRes) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRes.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRes proto.InternalMessageInfo

func (m *LoginRes) GetRetCode() ReturnCode {
	if m != nil {
		return m.RetCode
	}
	return ReturnCode_retOK
}

func (m *LoginRes) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *LoginRes) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Location struct {
	X                    int32    `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y                    int32    `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
	Z                    int32    `protobuf:"varint,3,opt,name=z,proto3" json:"z,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Location) Reset()         { *m = Location{} }
func (m *Location) String() string { return proto.CompactTextString(m) }
func (*Location) ProtoMessage()    {}
func (*Location) Descriptor() ([]byte, []int) {
	return fileDescriptor_67c21677aa7f4e4f, []int{2}
}

func (m *Location) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Location.Unmarshal(m, b)
}
func (m *Location) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Location.Marshal(b, m, deterministic)
}
func (m *Location) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Location.Merge(m, src)
}
func (m *Location) XXX_Size() int {
	return xxx_messageInfo_Location.Size(m)
}
func (m *Location) XXX_DiscardUnknown() {
	xxx_messageInfo_Location.DiscardUnknown(m)
}

var xxx_messageInfo_Location proto.InternalMessageInfo

func (m *Location) GetX() int32 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *Location) GetY() int32 {
	if m != nil {
		return m.Y
	}
	return 0
}

func (m *Location) GetZ() int32 {
	if m != nil {
		return m.Z
	}
	return 0
}

type UserInfo struct {
	Uid                  int64     `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Name                 string    `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Location             *Location `protobuf:"bytes,3,opt,name=location,proto3" json:"location,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *UserInfo) Reset()         { *m = UserInfo{} }
func (m *UserInfo) String() string { return proto.CompactTextString(m) }
func (*UserInfo) ProtoMessage()    {}
func (*UserInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_67c21677aa7f4e4f, []int{3}
}

func (m *UserInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserInfo.Unmarshal(m, b)
}
func (m *UserInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserInfo.Marshal(b, m, deterministic)
}
func (m *UserInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserInfo.Merge(m, src)
}
func (m *UserInfo) XXX_Size() int {
	return xxx_messageInfo_UserInfo.Size(m)
}
func (m *UserInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_UserInfo.DiscardUnknown(m)
}

var xxx_messageInfo_UserInfo proto.InternalMessageInfo

func (m *UserInfo) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *UserInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UserInfo) GetLocation() *Location {
	if m != nil {
		return m.Location
	}
	return nil
}

type RoomEnterReq struct {
	Uid                  int64    `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RoomEnterReq) Reset()         { *m = RoomEnterReq{} }
func (m *RoomEnterReq) String() string { return proto.CompactTextString(m) }
func (*RoomEnterReq) ProtoMessage()    {}
func (*RoomEnterReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_67c21677aa7f4e4f, []int{4}
}

func (m *RoomEnterReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoomEnterReq.Unmarshal(m, b)
}
func (m *RoomEnterReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoomEnterReq.Marshal(b, m, deterministic)
}
func (m *RoomEnterReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoomEnterReq.Merge(m, src)
}
func (m *RoomEnterReq) XXX_Size() int {
	return xxx_messageInfo_RoomEnterReq.Size(m)
}
func (m *RoomEnterReq) XXX_DiscardUnknown() {
	xxx_messageInfo_RoomEnterReq.DiscardUnknown(m)
}

var xxx_messageInfo_RoomEnterReq proto.InternalMessageInfo

func (m *RoomEnterReq) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

type RoomEnterRes struct {
	RetCode              ReturnCode `protobuf:"varint,1,opt,name=retCode,proto3,enum=packet.returncode.ReturnCode" json:"retCode,omitempty"`
	RoomID               int32      `protobuf:"varint,2,opt,name=roomID,proto3" json:"roomID,omitempty"`
	RoomName             string     `protobuf:"bytes,3,opt,name=roomName,proto3" json:"roomName,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *RoomEnterRes) Reset()         { *m = RoomEnterRes{} }
func (m *RoomEnterRes) String() string { return proto.CompactTextString(m) }
func (*RoomEnterRes) ProtoMessage()    {}
func (*RoomEnterRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_67c21677aa7f4e4f, []int{5}
}

func (m *RoomEnterRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoomEnterRes.Unmarshal(m, b)
}
func (m *RoomEnterRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoomEnterRes.Marshal(b, m, deterministic)
}
func (m *RoomEnterRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoomEnterRes.Merge(m, src)
}
func (m *RoomEnterRes) XXX_Size() int {
	return xxx_messageInfo_RoomEnterRes.Size(m)
}
func (m *RoomEnterRes) XXX_DiscardUnknown() {
	xxx_messageInfo_RoomEnterRes.DiscardUnknown(m)
}

var xxx_messageInfo_RoomEnterRes proto.InternalMessageInfo

func (m *RoomEnterRes) GetRetCode() ReturnCode {
	if m != nil {
		return m.RetCode
	}
	return ReturnCode_retOK
}

func (m *RoomEnterRes) GetRoomID() int32 {
	if m != nil {
		return m.RoomID
	}
	return 0
}

func (m *RoomEnterRes) GetRoomName() string {
	if m != nil {
		return m.RoomName
	}
	return ""
}

type RoomEnterNfy struct {
	UserInfoList         []*UserInfo `protobuf:"bytes,1,rep,name=UserInfoList,proto3" json:"UserInfoList,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *RoomEnterNfy) Reset()         { *m = RoomEnterNfy{} }
func (m *RoomEnterNfy) String() string { return proto.CompactTextString(m) }
func (*RoomEnterNfy) ProtoMessage()    {}
func (*RoomEnterNfy) Descriptor() ([]byte, []int) {
	return fileDescriptor_67c21677aa7f4e4f, []int{6}
}

func (m *RoomEnterNfy) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoomEnterNfy.Unmarshal(m, b)
}
func (m *RoomEnterNfy) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoomEnterNfy.Marshal(b, m, deterministic)
}
func (m *RoomEnterNfy) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoomEnterNfy.Merge(m, src)
}
func (m *RoomEnterNfy) XXX_Size() int {
	return xxx_messageInfo_RoomEnterNfy.Size(m)
}
func (m *RoomEnterNfy) XXX_DiscardUnknown() {
	xxx_messageInfo_RoomEnterNfy.DiscardUnknown(m)
}

var xxx_messageInfo_RoomEnterNfy proto.InternalMessageInfo

func (m *RoomEnterNfy) GetUserInfoList() []*UserInfo {
	if m != nil {
		return m.UserInfoList
	}
	return nil
}

type ReadyForGameReq struct {
	Uid                  int64    `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadyForGameReq) Reset()         { *m = ReadyForGameReq{} }
func (m *ReadyForGameReq) String() string { return proto.CompactTextString(m) }
func (*ReadyForGameReq) ProtoMessage()    {}
func (*ReadyForGameReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_67c21677aa7f4e4f, []int{7}
}

func (m *ReadyForGameReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadyForGameReq.Unmarshal(m, b)
}
func (m *ReadyForGameReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadyForGameReq.Marshal(b, m, deterministic)
}
func (m *ReadyForGameReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadyForGameReq.Merge(m, src)
}
func (m *ReadyForGameReq) XXX_Size() int {
	return xxx_messageInfo_ReadyForGameReq.Size(m)
}
func (m *ReadyForGameReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadyForGameReq.DiscardUnknown(m)
}

var xxx_messageInfo_ReadyForGameReq proto.InternalMessageInfo

func (m *ReadyForGameReq) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

type RoomLeaveReq struct {
	Uid                  int64    `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RoomLeaveReq) Reset()         { *m = RoomLeaveReq{} }
func (m *RoomLeaveReq) String() string { return proto.CompactTextString(m) }
func (*RoomLeaveReq) ProtoMessage()    {}
func (*RoomLeaveReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_67c21677aa7f4e4f, []int{8}
}

func (m *RoomLeaveReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoomLeaveReq.Unmarshal(m, b)
}
func (m *RoomLeaveReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoomLeaveReq.Marshal(b, m, deterministic)
}
func (m *RoomLeaveReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoomLeaveReq.Merge(m, src)
}
func (m *RoomLeaveReq) XXX_Size() int {
	return xxx_messageInfo_RoomLeaveReq.Size(m)
}
func (m *RoomLeaveReq) XXX_DiscardUnknown() {
	xxx_messageInfo_RoomLeaveReq.DiscardUnknown(m)
}

var xxx_messageInfo_RoomLeaveReq proto.InternalMessageInfo

func (m *RoomLeaveReq) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

type RoomLeaveRes struct {
	RetCode              ReturnCode `protobuf:"varint,1,opt,name=retCode,proto3,enum=packet.returncode.ReturnCode" json:"retCode,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *RoomLeaveRes) Reset()         { *m = RoomLeaveRes{} }
func (m *RoomLeaveRes) String() string { return proto.CompactTextString(m) }
func (*RoomLeaveRes) ProtoMessage()    {}
func (*RoomLeaveRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_67c21677aa7f4e4f, []int{9}
}

func (m *RoomLeaveRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoomLeaveRes.Unmarshal(m, b)
}
func (m *RoomLeaveRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoomLeaveRes.Marshal(b, m, deterministic)
}
func (m *RoomLeaveRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoomLeaveRes.Merge(m, src)
}
func (m *RoomLeaveRes) XXX_Size() int {
	return xxx_messageInfo_RoomLeaveRes.Size(m)
}
func (m *RoomLeaveRes) XXX_DiscardUnknown() {
	xxx_messageInfo_RoomLeaveRes.DiscardUnknown(m)
}

var xxx_messageInfo_RoomLeaveRes proto.InternalMessageInfo

func (m *RoomLeaveRes) GetRetCode() ReturnCode {
	if m != nil {
		return m.RetCode
	}
	return ReturnCode_retOK
}

type RoomLeaveNfy struct {
	UserInfoList         []*UserInfo `protobuf:"bytes,1,rep,name=UserInfoList,proto3" json:"UserInfoList,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *RoomLeaveNfy) Reset()         { *m = RoomLeaveNfy{} }
func (m *RoomLeaveNfy) String() string { return proto.CompactTextString(m) }
func (*RoomLeaveNfy) ProtoMessage()    {}
func (*RoomLeaveNfy) Descriptor() ([]byte, []int) {
	return fileDescriptor_67c21677aa7f4e4f, []int{10}
}

func (m *RoomLeaveNfy) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoomLeaveNfy.Unmarshal(m, b)
}
func (m *RoomLeaveNfy) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoomLeaveNfy.Marshal(b, m, deterministic)
}
func (m *RoomLeaveNfy) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoomLeaveNfy.Merge(m, src)
}
func (m *RoomLeaveNfy) XXX_Size() int {
	return xxx_messageInfo_RoomLeaveNfy.Size(m)
}
func (m *RoomLeaveNfy) XXX_DiscardUnknown() {
	xxx_messageInfo_RoomLeaveNfy.DiscardUnknown(m)
}

var xxx_messageInfo_RoomLeaveNfy proto.InternalMessageInfo

func (m *RoomLeaveNfy) GetUserInfoList() []*UserInfo {
	if m != nil {
		return m.UserInfoList
	}
	return nil
}

func init() {
	proto.RegisterType((*LoginReq)(nil), "packet.lobby.LoginReq")
	proto.RegisterType((*LoginRes)(nil), "packet.lobby.LoginRes")
	proto.RegisterType((*Location)(nil), "packet.lobby.Location")
	proto.RegisterType((*UserInfo)(nil), "packet.lobby.UserInfo")
	proto.RegisterType((*RoomEnterReq)(nil), "packet.lobby.RoomEnterReq")
	proto.RegisterType((*RoomEnterRes)(nil), "packet.lobby.RoomEnterRes")
	proto.RegisterType((*RoomEnterNfy)(nil), "packet.lobby.RoomEnterNfy")
	proto.RegisterType((*ReadyForGameReq)(nil), "packet.lobby.ReadyForGameReq")
	proto.RegisterType((*RoomLeaveReq)(nil), "packet.lobby.RoomLeaveReq")
	proto.RegisterType((*RoomLeaveRes)(nil), "packet.lobby.RoomLeaveRes")
	proto.RegisterType((*RoomLeaveNfy)(nil), "packet.lobby.RoomLeaveNfy")
}

func init() { proto.RegisterFile("login.proto", fileDescriptor_67c21677aa7f4e4f) }

var fileDescriptor_67c21677aa7f4e4f = []byte{
	// 333 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x92, 0x4f, 0x6b, 0xf2, 0x40,
	0x10, 0x87, 0x59, 0xf3, 0xea, 0x9b, 0x8e, 0xa1, 0x95, 0x3d, 0x88, 0x08, 0x2d, 0x61, 0x7b, 0xf1,
	0x94, 0x83, 0x2d, 0x14, 0x7a, 0xed, 0x1f, 0xb1, 0x88, 0x87, 0x81, 0x7e, 0x80, 0x68, 0xd6, 0x12,
	0x6a, 0x32, 0x76, 0x5d, 0x8b, 0xb1, 0x5f, 0xbe, 0xec, 0x9a, 0xc4, 0x48, 0xda, 0x4b, 0xbd, 0xcd,
	0xb0, 0xcf, 0xcc, 0x93, 0xf9, 0x11, 0x68, 0x2f, 0xe9, 0x2d, 0x4e, 0x83, 0x95, 0x22, 0x4d, 0xdc,
	0x5b, 0x85, 0xf3, 0x77, 0xa9, 0x83, 0x25, 0xcd, 0x66, 0x59, 0xbf, 0xa3, 0xa4, 0xde, 0xa8, 0x74,
	0x4e, 0x91, 0xdc, 0xbf, 0x8b, 0x2b, 0x70, 0x27, 0x06, 0x47, 0xf9, 0xc1, 0x39, 0xfc, 0x4b, 0xc3,
	0x44, 0xf6, 0x98, 0xcf, 0x06, 0x67, 0x68, 0x6b, 0x11, 0x97, 0xef, 0x6b, 0x7e, 0x07, 0xff, 0x95,
	0xd4, 0x0f, 0x14, 0xed, 0x91, 0xf3, 0xe1, 0x65, 0x90, 0x6f, 0xaf, 0xac, 0x45, 0x5b, 0x1a, 0x08,
	0x0b, 0x9a, 0x77, 0xc0, 0xd9, 0xc4, 0x51, 0xaf, 0xe1, 0xb3, 0x81, 0x83, 0xa6, 0x2c, 0x55, 0x4e,
	0x45, 0x75, 0x6b, 0x54, 0xf3, 0x50, 0xc7, 0x94, 0x72, 0x0f, 0xd8, 0xd6, 0x4a, 0x9a, 0xc8, 0xb6,
	0xa6, 0xcb, 0xec, 0x74, 0x13, 0x59, 0x66, 0xba, 0x9d, 0x1d, 0x6c, 0x22, 0xdb, 0x89, 0x08, 0xdc,
	0xd7, 0xb5, 0x54, 0xe3, 0x74, 0x41, 0x85, 0x87, 0xd5, 0x3d, 0x8d, 0x83, 0x87, 0x0f, 0xc1, 0x5d,
	0xe6, 0x1e, 0xbb, 0xa6, 0x3d, 0xec, 0x06, 0xd5, 0x94, 0x82, 0xe2, 0x2b, 0xb0, 0xe4, 0x84, 0x0f,
	0x1e, 0x12, 0x25, 0x4f, 0xa9, 0x96, 0xca, 0x44, 0x55, 0x33, 0x89, 0xaf, 0x23, 0xe2, 0x84, 0xb0,
	0xba, 0xd0, 0x52, 0x44, 0xc9, 0xf8, 0x31, 0xbf, 0x38, 0xef, 0x78, 0x1f, 0x5c, 0x53, 0x4d, 0x0f,
	0xb1, 0x95, 0xbd, 0x78, 0xa9, 0xc8, 0xa7, 0x8b, 0x8c, 0xdf, 0x83, 0x57, 0x84, 0x32, 0x89, 0xd7,
	0xba, 0xc7, 0x7c, 0xa7, 0x7e, 0x66, 0x41, 0xe0, 0x11, 0x2b, 0xae, 0xe1, 0x02, 0x65, 0x18, 0x65,
	0xcf, 0xa4, 0x46, 0x61, 0x22, 0x7f, 0xbe, 0x36, 0xcf, 0x63, 0x22, 0xc3, 0xcf, 0x5f, 0x88, 0xd1,
	0x11, 0xf1, 0xf7, 0x3c, 0x8a, 0xdb, 0xec, 0xa2, 0x13, 0x6f, 0x9b, 0xb5, 0xec, 0x4f, 0x7f, 0xf3,
	0x1d, 0x00, 0x00, 0xff, 0xff, 0xc1, 0xc2, 0x5e, 0xf7, 0x23, 0x03, 0x00, 0x00,
}
