// Code generated by protoc-gen-go. DO NOT EDIT.
// source: login.proto

package main

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ReturnCode int32

const (
	ReturnCode_retOK    ReturnCode = 0
	ReturnCode_retFail  ReturnCode = 1
	ReturnCode_retExist ReturnCode = 1001
)

var ReturnCode_name = map[int32]string{
	0:    "retOK",
	1:    "retFail",
	1001: "retExist",
}

var ReturnCode_value = map[string]int32{
	"retOK":    0,
	"retFail":  1,
	"retExist": 1001,
}

func (x ReturnCode) String() string {
	return proto.EnumName(ReturnCode_name, int32(x))
}

func (ReturnCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_67c21677aa7f4e4f, []int{0}
}

type LoginReq struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginReq) Reset()         { *m = LoginReq{} }
func (m *LoginReq) String() string { return proto.CompactTextString(m) }
func (*LoginReq) ProtoMessage()    {}
func (*LoginReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_67c21677aa7f4e4f, []int{0}
}

func (m *LoginReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginReq.Unmarshal(m, b)
}
func (m *LoginReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginReq.Marshal(b, m, deterministic)
}
func (m *LoginReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginReq.Merge(m, src)
}
func (m *LoginReq) XXX_Size() int {
	return xxx_messageInfo_LoginReq.Size(m)
}
func (m *LoginReq) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginReq.DiscardUnknown(m)
}

var xxx_messageInfo_LoginReq proto.InternalMessageInfo

func (m *LoginReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type LoginRes struct {
	RetCode              ReturnCode `protobuf:"varint,1,opt,name=retCode,proto3,enum=main.ReturnCode" json:"retCode,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *LoginRes) Reset()         { *m = LoginRes{} }
func (m *LoginRes) String() string { return proto.CompactTextString(m) }
func (*LoginRes) ProtoMessage()    {}
func (*LoginRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_67c21677aa7f4e4f, []int{1}
}

func (m *LoginRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRes.Unmarshal(m, b)
}
func (m *LoginRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRes.Marshal(b, m, deterministic)
}
func (m *LoginRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRes.Merge(m, src)
}
func (m *LoginRes) XXX_Size() int {
	return xxx_messageInfo_LoginRes.Size(m)
}
func (m *LoginRes) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRes.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRes proto.InternalMessageInfo

func (m *LoginRes) GetRetCode() ReturnCode {
	if m != nil {
		return m.RetCode
	}
	return ReturnCode_retOK
}

func init() {
	proto.RegisterEnum("main.ReturnCode", ReturnCode_name, ReturnCode_value)
	proto.RegisterType((*LoginReq)(nil), "main.LoginReq")
	proto.RegisterType((*LoginRes)(nil), "main.LoginRes")
}

func init() { proto.RegisterFile("login.proto", fileDescriptor_67c21677aa7f4e4f) }

var fileDescriptor_67c21677aa7f4e4f = []byte{
	// 152 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xce, 0xc9, 0x4f, 0xcf,
	0xcc, 0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xc9, 0x4d, 0xcc, 0xcc, 0x53, 0x92, 0xe3,
	0xe2, 0xf0, 0x01, 0x09, 0x06, 0xa5, 0x16, 0x0a, 0x09, 0x71, 0xb1, 0xe4, 0x25, 0xe6, 0xa6, 0x4a,
	0x30, 0x2a, 0x30, 0x6a, 0x70, 0x06, 0x81, 0xd9, 0x4a, 0x66, 0x70, 0xf9, 0x62, 0x21, 0x2d, 0x2e,
	0xf6, 0xa2, 0xd4, 0x12, 0xe7, 0xfc, 0x14, 0x88, 0x12, 0x3e, 0x23, 0x01, 0x3d, 0x90, 0x19, 0x7a,
	0x41, 0xa9, 0x25, 0xa5, 0x45, 0x79, 0x20, 0xf1, 0x20, 0x98, 0x02, 0x2d, 0x63, 0x2e, 0x2e, 0x84,
	0xb0, 0x10, 0x27, 0x17, 0x6b, 0x51, 0x6a, 0x89, 0xbf, 0xb7, 0x00, 0x83, 0x10, 0x37, 0xd8, 0x10,
	0xb7, 0xc4, 0xcc, 0x1c, 0x01, 0x46, 0x21, 0x5e, 0x2e, 0x8e, 0xa2, 0xd4, 0x12, 0xd7, 0x8a, 0xcc,
	0xe2, 0x12, 0x81, 0x97, 0xec, 0x49, 0x6c, 0x60, 0x97, 0x19, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff,
	0x7e, 0x18, 0x6d, 0x6e, 0xa8, 0x00, 0x00, 0x00,
}
