name: Go
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.17
      uses: actions/setup-go@v1
      with:
        go-version: 1.17
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Display path
      run: pwd
      
    - name: Display files
      run: ls -al
      
    - name: Build server      
      run: go build -v ./src/toy_io_server